### ISSUE TITLE
Entire Trails (Track chains) disappear randomly

### ISSUE THREAD

**Issue by johnwdubois** [johnwdubois/rezonator#823] opened 2021-03-09 14:47 UTC
**Bug**
_**NOTE:**_ This is a serious bug, now confirmed by several users, which needs immediate attention.    
When making a few Trails with one or more Tracks each, and then deleting words occasionally from a Trail, sometimes a whole Trail disappears completely. 
Often, there is a residue: Some words from the former Trail still have word-boxes drawn around them. But these cannot be deleted. Also, the words cannot be added to any other trail.
The conditions that lead to this are difficult to reproduce, but often seem to involve deleting a chunk from a trail.

**Test**
It may be useful to automatically generate large numbers of random links, and delete some of them randomly, to attempt to reproduce the problem.

**Comment by kayaulai** [comment] 2021-04-01 00:47
Sorry, but this still seems to be happening. I think it is most common when removing a chunk from the trail.

**Comment by kayaulai** [comment] 2021-04-01 08:32
I have just had another case where the chain had two members left (both non-chunk) after I added the latest addition (a chunk). The chain disappeared from the list of chains, but then the words still had coloured boxes around them, even though they can't be focused or removed by clicking Delete Link. Nor am I able to add them to a another chain.  So unfortunately this bug still very much seems to be around.

**Comment by kayaulai** [comment] 2021-04-01 08:49
It's hard to give steps to reproduce the bug, but I've attached a Rez file (inside a Zip because Git doesn't accept Rez uploads). Lines 32, 33 and 42 illustrate this problem.

[dramatroupe-interview-2719.zip](https://github.com/johnwdubois/rezonator/files/6242284/dramatroupe-interview-2719.zip)

**Comment by hopesu21** [comment] 2021-04-07 06:01
According to Terry and Brady, this is now fixed.

**Closed by hopesu21** 2021-04-07 06:01 UTC
Labels: bug
