### ISSUE TITLE
Rez Chain Dropdown

### ISSUE THREAD

**Issue by AvivSamet** [johnwdubois/rezonator#678] opened 2020-10-28 00:00 UTC
**What is the background of this bug report?**

Right clicking on a link in a rez chain near the bottom of the screen/main window throws out 5 errors and doesn't open a dropdown menu.

**To Reproduce**

1. Create a Rez Chain
2. Right Click on a link near the bottom of the screen

**Describe what to do for the desired behavior**

**Screenshots**

![error1](https://user-images.githubusercontent.com/59664942/97374300-3c7d0a80-1875-11eb-8b0c-0ef53e76a0cf.PNG)
![error2](https://user-images.githubusercontent.com/59664942/97374301-3d15a100-1875-11eb-81bf-b19393bd5b9a.PNG)
![error3](https://user-images.githubusercontent.com/59664942/97374302-3d15a100-1875-11eb-9107-71935a9007e8.PNG)
![error4](https://user-images.githubusercontent.com/59664942/97374303-3d15a100-1875-11eb-898e-11a4671778b9.PNG)
![error5](https://user-images.githubusercontent.com/59664942/97374305-3d15a100-1875-11eb-846d-7eb26979ba3d.PNG)

**Desktop (please complete the following information):**
OS: Windows 10
Version: 2004
Build: 19041.572

**What is the estimated development time?**
An estimate in hours. Ex. 2.5 hours, 6 hours.

**Describe the individual development tasks that make up this feature (along with a dev hour estimate)**
- [ ] Example Task - 1 hr
- [ ] Example Task- 2 hr
- [ ] Example Task- 3 hr
- [ ] Example Task - 4 hr

**Comment by Georgio-Klironomos** [comment] 2020-11-03 01:43
@AvivSamet This error was being caused by the dropdown's being "drawn" offscreen. It's been fixed by keeping dropdowns on the viewable screen. This fix will be included in the next release.

**Closed** 2020-11-10 22:45 UTC
Labels: bug
